export const LOAD_DATA_INITIATION = 'LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';
export const CLEAR_DATA_ERROR = 'CLEAR_DATA_ERROR';
