/* Constants for displaying and clearing errors and messages for amazing component. */
export const AMAZING_COMPONENT_ERROR = 'AMAZING_COMPONENT_ERROR';
export const AMAZING_COMPONENT_MESSAGE = 'AMAZING_COMPONENT_MESSAGE';
export const CLEAR_AMAZING_COMPONENT_ERROR = 'CLEAR_AMAZING_COMPONENT_ERROR';
export const CLEAR_AMAZING_COMPONENT_MESSAGE = 'CLEAR_AMAZING_COMPONENT_MESSAGE';
