// flow-typed signature: 304a7294385bdf318b06ba956fc6569c
// flow-typed version: <<STUB>>/actions_v^1.3.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'actions/index' {
  declare module.exports: $Exports<'actions'>;
}
declare module 'actions/index.js' {
  declare module.exports: $Exports<'actions'>;
}
