// flow-typed signature: ff90cdb86379e7d59913ca4ba2f763c2
// flow-typed version: <<STUB>>/apollo-client_v^0.5.20/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-client/actions' {
  declare module.exports: any;
}

declare module 'apollo-client/ApolloClient' {
  declare module.exports: any;
}

declare module 'apollo-client/core/ObservableQuery' {
  declare module.exports: any;
}

declare module 'apollo-client/core/QueryManager' {
  declare module.exports: any;
}

declare module 'apollo-client/core/watchQueryOptions' {
  declare module.exports: any;
}

declare module 'apollo-client/data/extensions' {
  declare module.exports: any;
}

declare module 'apollo-client/data/mutationResults' {
  declare module.exports: any;
}

declare module 'apollo-client/data/readFromStore' {
  declare module.exports: any;
}

declare module 'apollo-client/data/replaceQueryResults' {
  declare module.exports: any;
}

declare module 'apollo-client/data/resultReducers' {
  declare module.exports: any;
}

declare module 'apollo-client/data/scopeQuery' {
  declare module.exports: any;
}

declare module 'apollo-client/data/store' {
  declare module.exports: any;
}

declare module 'apollo-client/data/storeUtils' {
  declare module.exports: any;
}

declare module 'apollo-client/data/writeToStore' {
  declare module.exports: any;
}

declare module 'apollo-client/errors/ApolloError' {
  declare module.exports: any;
}

declare module 'apollo-client/fragments' {
  declare module.exports: any;
}

declare module 'apollo-client/mutations/store' {
  declare module.exports: any;
}

declare module 'apollo-client/optimistic-data/store' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/directives' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/getFromAST' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/queryTransform' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/store' {
  declare module.exports: any;
}

declare module 'apollo-client/scheduler/scheduler' {
  declare module.exports: any;
}

declare module 'apollo-client/store' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/afterware' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/batchedNetworkInterface' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/batching' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/middleware' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/networkInterface' {
  declare module.exports: any;
}

declare module 'apollo-client/util/errorHandling' {
  declare module.exports: any;
}

declare module 'apollo-client/util/Observable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-client/actions.js' {
  declare module.exports: $Exports<'apollo-client/actions'>;
}
declare module 'apollo-client/ApolloClient.js' {
  declare module.exports: $Exports<'apollo-client/ApolloClient'>;
}
declare module 'apollo-client/core/ObservableQuery.js' {
  declare module.exports: $Exports<'apollo-client/core/ObservableQuery'>;
}
declare module 'apollo-client/core/QueryManager.js' {
  declare module.exports: $Exports<'apollo-client/core/QueryManager'>;
}
declare module 'apollo-client/core/watchQueryOptions.js' {
  declare module.exports: $Exports<'apollo-client/core/watchQueryOptions'>;
}
declare module 'apollo-client/data/extensions.js' {
  declare module.exports: $Exports<'apollo-client/data/extensions'>;
}
declare module 'apollo-client/data/mutationResults.js' {
  declare module.exports: $Exports<'apollo-client/data/mutationResults'>;
}
declare module 'apollo-client/data/readFromStore.js' {
  declare module.exports: $Exports<'apollo-client/data/readFromStore'>;
}
declare module 'apollo-client/data/replaceQueryResults.js' {
  declare module.exports: $Exports<'apollo-client/data/replaceQueryResults'>;
}
declare module 'apollo-client/data/resultReducers.js' {
  declare module.exports: $Exports<'apollo-client/data/resultReducers'>;
}
declare module 'apollo-client/data/scopeQuery.js' {
  declare module.exports: $Exports<'apollo-client/data/scopeQuery'>;
}
declare module 'apollo-client/data/store.js' {
  declare module.exports: $Exports<'apollo-client/data/store'>;
}
declare module 'apollo-client/data/storeUtils.js' {
  declare module.exports: $Exports<'apollo-client/data/storeUtils'>;
}
declare module 'apollo-client/data/writeToStore.js' {
  declare module.exports: $Exports<'apollo-client/data/writeToStore'>;
}
declare module 'apollo-client/errors/ApolloError.js' {
  declare module.exports: $Exports<'apollo-client/errors/ApolloError'>;
}
declare module 'apollo-client/fragments.js' {
  declare module.exports: $Exports<'apollo-client/fragments'>;
}
declare module 'apollo-client/index' {
  declare module.exports: $Exports<'apollo-client'>;
}
declare module 'apollo-client/index.js' {
  declare module.exports: $Exports<'apollo-client'>;
}
declare module 'apollo-client/mutations/store.js' {
  declare module.exports: $Exports<'apollo-client/mutations/store'>;
}
declare module 'apollo-client/optimistic-data/store.js' {
  declare module.exports: $Exports<'apollo-client/optimistic-data/store'>;
}
declare module 'apollo-client/queries/directives.js' {
  declare module.exports: $Exports<'apollo-client/queries/directives'>;
}
declare module 'apollo-client/queries/getFromAST.js' {
  declare module.exports: $Exports<'apollo-client/queries/getFromAST'>;
}
declare module 'apollo-client/queries/queryTransform.js' {
  declare module.exports: $Exports<'apollo-client/queries/queryTransform'>;
}
declare module 'apollo-client/queries/store.js' {
  declare module.exports: $Exports<'apollo-client/queries/store'>;
}
declare module 'apollo-client/scheduler/scheduler.js' {
  declare module.exports: $Exports<'apollo-client/scheduler/scheduler'>;
}
declare module 'apollo-client/store.js' {
  declare module.exports: $Exports<'apollo-client/store'>;
}
declare module 'apollo-client/transport/afterware.js' {
  declare module.exports: $Exports<'apollo-client/transport/afterware'>;
}
declare module 'apollo-client/transport/batchedNetworkInterface.js' {
  declare module.exports: $Exports<'apollo-client/transport/batchedNetworkInterface'>;
}
declare module 'apollo-client/transport/batching.js' {
  declare module.exports: $Exports<'apollo-client/transport/batching'>;
}
declare module 'apollo-client/transport/middleware.js' {
  declare module.exports: $Exports<'apollo-client/transport/middleware'>;
}
declare module 'apollo-client/transport/networkInterface.js' {
  declare module.exports: $Exports<'apollo-client/transport/networkInterface'>;
}
declare module 'apollo-client/util/errorHandling.js' {
  declare module.exports: $Exports<'apollo-client/util/errorHandling'>;
}
declare module 'apollo-client/util/Observable.js' {
  declare module.exports: $Exports<'apollo-client/util/Observable'>;
}
