// flow-typed signature: fba96d9949fef546474e3f3173b75a71
// flow-typed version: <<STUB>>/components_v^0.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'components/assets/highlight' {
  declare module.exports: any;
}

declare module 'components/assets/holder' {
  declare module.exports: any;
}

declare module 'components/Gruntfile' {
  declare module.exports: any;
}

declare module 'components/src/helpers/helpers' {
  declare module.exports: any;
}

declare module 'components/src/helpers/mixins' {
  declare module.exports: any;
}

declare module 'components/vendor/jquery/jquery' {
  declare module.exports: any;
}

declare module 'components/vendor/jquery/jquery.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'components/assets/highlight.js' {
  declare module.exports: $Exports<'components/assets/highlight'>;
}
declare module 'components/assets/holder.js' {
  declare module.exports: $Exports<'components/assets/holder'>;
}
declare module 'components/Gruntfile.js' {
  declare module.exports: $Exports<'components/Gruntfile'>;
}
declare module 'components/src/helpers/helpers.js' {
  declare module.exports: $Exports<'components/src/helpers/helpers'>;
}
declare module 'components/src/helpers/mixins.js' {
  declare module.exports: $Exports<'components/src/helpers/mixins'>;
}
declare module 'components/vendor/jquery/jquery.js' {
  declare module.exports: $Exports<'components/vendor/jquery/jquery'>;
}
declare module 'components/vendor/jquery/jquery.min.js' {
  declare module.exports: $Exports<'components/vendor/jquery/jquery.min'>;
}
