// flow-typed signature: 4c0718cef02f58be1a530844e3e9d642
// flow-typed version: <<STUB>>/expect-jsx_v^2.6.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expect-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'expect-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expect-jsx/index-dist' {
  declare module.exports: any;
}

declare module 'expect-jsx/index-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expect-jsx/index-dist.js' {
  declare module.exports: $Exports<'expect-jsx/index-dist'>;
}
declare module 'expect-jsx/index-test.js' {
  declare module.exports: $Exports<'expect-jsx/index-test'>;
}
declare module 'expect-jsx/index' {
  declare module.exports: $Exports<'expect-jsx'>;
}
declare module 'expect-jsx/index.js' {
  declare module.exports: $Exports<'expect-jsx'>;
}
