// flow-typed signature: 190e637959abd030cd9fbb4d25991fe3
// flow-typed version: <<STUB>>/foundation-sites_v^6.2.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'foundation-sites'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'foundation-sites' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'foundation-sites/dist/foundation' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/foundation.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.abide' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.accordion' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.accordionMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.core' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.drilldown' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.dropdown' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.dropdownMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.equalizer' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.interchange' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.magellan' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.offcanvas' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.orbit' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.responsiveMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.responsiveToggle' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.reveal' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.slider' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.sticky' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.tabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.toggler' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.tooltip' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.util.box' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.util.keyboard' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.util.mediaQuery' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.util.motion' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.util.nest' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.util.timerAndImageLoader' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.util.touch' {
  declare module.exports: any;
}

declare module 'foundation-sites/dist/plugins/foundation.util.triggers' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.abide' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.accordion' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.accordionMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.core' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.drilldown' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.dropdown' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.dropdownMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.equalizer' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.interchange' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.magellan' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.offcanvas' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.orbit' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.responsiveMenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.responsiveToggle' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.reveal' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.slider' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.sticky' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.tabs' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.toggler' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.tooltip' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.box' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.keyboard' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.mediaQuery' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.motion' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.nest' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.timerAndImageLoader' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.touch' {
  declare module.exports: any;
}

declare module 'foundation-sites/js/foundation.util.triggers' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery-placeholder/jquery.placeholder' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery.autocomplete/dist/jquery.autocomplete' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery.autocomplete/dist/jquery.autocomplete.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery.autocomplete/scripts/countries' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery.autocomplete/scripts/demo' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery.autocomplete/scripts/jquery-1.8.2.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery.autocomplete/scripts/jquery.mockjax' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery.autocomplete/src/jquery.autocomplete' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery.cookie/jquery.cookie' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/dist/jquery' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/dist/jquery.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax/jsonp' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax/load' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax/parseJSON' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax/parseXML' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax/script' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax/var/nonce' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax/var/rquery' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/ajax/xhr' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/attributes' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/attributes/attr' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/attributes/classes' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/attributes/prop' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/attributes/support' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/attributes/val' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/callbacks' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/core' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/core/access' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/core/init' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/core/parseHTML' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/core/ready' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/core/var/rsingleTag' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/addGetHookIf' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/curCSS' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/defaultDisplay' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/hiddenVisibleSelectors' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/support' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/swap' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/var/cssExpand' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/var/getStyles' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/var/isHidden' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/var/rmargin' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/css/var/rnumnonpx' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/data' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/data/accepts' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/data/Data' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/data/var/data_priv' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/data/var/data_user' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/deferred' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/deprecated' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/dimensions' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/effects' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/effects/animatedSelector' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/effects/Tween' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/event' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/event/ajax' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/event/alias' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/event/support' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/exports/amd' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/exports/global' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/intro' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/jquery' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/manipulation' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/manipulation/_evalUrl' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/manipulation/support' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/manipulation/var/rcheckableType' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/offset' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/outro' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/queue' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/queue/delay' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/selector-native' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/selector-sizzle' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/selector' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/serialize' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/sizzle/dist/sizzle' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/sizzle/dist/sizzle.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/traversing' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/traversing/findFilter' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/traversing/var/rneedsContext' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/arr' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/class2type' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/concat' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/hasOwn' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/indexOf' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/pnum' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/push' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/rnotwhite' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/slice' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/strundefined' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/support' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/var/toString' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/jquery/src/wrap' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/lodash/dist/lodash.compat' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/lodash/dist/lodash.compat.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/lodash/dist/lodash' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/lodash/dist/lodash.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/lodash/dist/lodash.underscore' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/lodash/dist/lodash.underscore.min' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/a-download' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/audio-audiodata-api' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/audio-webaudio-api' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/battery-api' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/battery-level' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/blob-constructor' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/canvas-todataurl-type' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/contenteditable' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/contentsecuritypolicy' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/contextmenu' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/cookies' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/cors' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-backgroundposition-shorthand' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-backgroundposition-xy' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-backgroundrepeat' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-backgroundsizecover' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-boxsizing' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-calc' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-cubicbezierrange' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-displayrunin' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-displaytable' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-filters' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-hyphens' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-lastchild' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-mask' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-mediaqueries' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-objectfit' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-overflow-scrolling' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-pointerevents' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-positionsticky' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-regions' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-remunit' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-resize' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-scrollbars' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-shapes' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-subpixelfont' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-supports' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-userselect' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-vhunit' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-vmaxunit' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-vminunit' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/css-vwunit' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/custom-protocol-handler' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/dart' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/dataview-api' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/dom-classlist' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/dom-createElement-attrs' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/dom-dataset' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/dom-microdata' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-datalist' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-details' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-output' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-progress-meter' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-ruby' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-time' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-track' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/emoji' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/es5-strictmode' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/event-deviceorientation-motion' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/exif-orientation' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/file-api' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/file-filesystem' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-fileinput' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-formattribute' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-inputnumber-l10n' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-placeholder' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-speechinput' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-validation' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/fullscreen-api' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/gamepad' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/getusermedia' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/ie8compat' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/iframe-sandbox' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/iframe-seamless' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/iframe-srcdoc' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/img-apng' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/img-webp' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/json' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/lists-reversed' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/mathml' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/network-connection' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/network-eventsource' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/network-xhr2' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/notification' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/performance' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/pointerlock-api' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/quota-management-api' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/requestanimationframe' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/script-async' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/script-defer' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/style-scoped' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/svg-filters' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/unicode' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/url-data-uri' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/userdata' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/vibration' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/web-intents' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/webgl-extensions' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/websockets-binary' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/window-framed' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/workers-blobworkers' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/workers-dataworkers' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/feature-detects/workers-sharedworkers' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/grunt' {
  declare module.exports: any;
}

declare module 'foundation-sites/vendor/modernizr/modernizr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'foundation-sites/dist/foundation.js' {
  declare module.exports: $Exports<'foundation-sites/dist/foundation'>;
}
declare module 'foundation-sites/dist/foundation.min.js' {
  declare module.exports: $Exports<'foundation-sites/dist/foundation.min'>;
}
declare module 'foundation-sites/dist/plugins/foundation.abide.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.abide'>;
}
declare module 'foundation-sites/dist/plugins/foundation.accordion.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.accordion'>;
}
declare module 'foundation-sites/dist/plugins/foundation.accordionMenu.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.accordionMenu'>;
}
declare module 'foundation-sites/dist/plugins/foundation.core.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.core'>;
}
declare module 'foundation-sites/dist/plugins/foundation.drilldown.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.drilldown'>;
}
declare module 'foundation-sites/dist/plugins/foundation.dropdown.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.dropdown'>;
}
declare module 'foundation-sites/dist/plugins/foundation.dropdownMenu.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.dropdownMenu'>;
}
declare module 'foundation-sites/dist/plugins/foundation.equalizer.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.equalizer'>;
}
declare module 'foundation-sites/dist/plugins/foundation.interchange.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.interchange'>;
}
declare module 'foundation-sites/dist/plugins/foundation.magellan.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.magellan'>;
}
declare module 'foundation-sites/dist/plugins/foundation.offcanvas.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.offcanvas'>;
}
declare module 'foundation-sites/dist/plugins/foundation.orbit.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.orbit'>;
}
declare module 'foundation-sites/dist/plugins/foundation.responsiveMenu.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.responsiveMenu'>;
}
declare module 'foundation-sites/dist/plugins/foundation.responsiveToggle.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.responsiveToggle'>;
}
declare module 'foundation-sites/dist/plugins/foundation.reveal.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.reveal'>;
}
declare module 'foundation-sites/dist/plugins/foundation.slider.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.slider'>;
}
declare module 'foundation-sites/dist/plugins/foundation.sticky.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.sticky'>;
}
declare module 'foundation-sites/dist/plugins/foundation.tabs.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.tabs'>;
}
declare module 'foundation-sites/dist/plugins/foundation.toggler.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.toggler'>;
}
declare module 'foundation-sites/dist/plugins/foundation.tooltip.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.tooltip'>;
}
declare module 'foundation-sites/dist/plugins/foundation.util.box.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.util.box'>;
}
declare module 'foundation-sites/dist/plugins/foundation.util.keyboard.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.util.keyboard'>;
}
declare module 'foundation-sites/dist/plugins/foundation.util.mediaQuery.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.util.mediaQuery'>;
}
declare module 'foundation-sites/dist/plugins/foundation.util.motion.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.util.motion'>;
}
declare module 'foundation-sites/dist/plugins/foundation.util.nest.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.util.nest'>;
}
declare module 'foundation-sites/dist/plugins/foundation.util.timerAndImageLoader.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.util.timerAndImageLoader'>;
}
declare module 'foundation-sites/dist/plugins/foundation.util.touch.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.util.touch'>;
}
declare module 'foundation-sites/dist/plugins/foundation.util.triggers.js' {
  declare module.exports: $Exports<'foundation-sites/dist/plugins/foundation.util.triggers'>;
}
declare module 'foundation-sites/js/foundation.abide.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.abide'>;
}
declare module 'foundation-sites/js/foundation.accordion.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.accordion'>;
}
declare module 'foundation-sites/js/foundation.accordionMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.accordionMenu'>;
}
declare module 'foundation-sites/js/foundation.core.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.core'>;
}
declare module 'foundation-sites/js/foundation.drilldown.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.drilldown'>;
}
declare module 'foundation-sites/js/foundation.dropdown.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.dropdown'>;
}
declare module 'foundation-sites/js/foundation.dropdownMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.dropdownMenu'>;
}
declare module 'foundation-sites/js/foundation.equalizer.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.equalizer'>;
}
declare module 'foundation-sites/js/foundation.interchange.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.interchange'>;
}
declare module 'foundation-sites/js/foundation.magellan.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.magellan'>;
}
declare module 'foundation-sites/js/foundation.offcanvas.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.offcanvas'>;
}
declare module 'foundation-sites/js/foundation.orbit.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.orbit'>;
}
declare module 'foundation-sites/js/foundation.responsiveMenu.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.responsiveMenu'>;
}
declare module 'foundation-sites/js/foundation.responsiveToggle.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.responsiveToggle'>;
}
declare module 'foundation-sites/js/foundation.reveal.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.reveal'>;
}
declare module 'foundation-sites/js/foundation.slider.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.slider'>;
}
declare module 'foundation-sites/js/foundation.sticky.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.sticky'>;
}
declare module 'foundation-sites/js/foundation.tabs.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.tabs'>;
}
declare module 'foundation-sites/js/foundation.toggler.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.toggler'>;
}
declare module 'foundation-sites/js/foundation.tooltip.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.tooltip'>;
}
declare module 'foundation-sites/js/foundation.util.box.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.box'>;
}
declare module 'foundation-sites/js/foundation.util.keyboard.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.keyboard'>;
}
declare module 'foundation-sites/js/foundation.util.mediaQuery.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.mediaQuery'>;
}
declare module 'foundation-sites/js/foundation.util.motion.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.motion'>;
}
declare module 'foundation-sites/js/foundation.util.nest.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.nest'>;
}
declare module 'foundation-sites/js/foundation.util.timerAndImageLoader.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.timerAndImageLoader'>;
}
declare module 'foundation-sites/js/foundation.util.touch.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.touch'>;
}
declare module 'foundation-sites/js/foundation.util.triggers.js' {
  declare module.exports: $Exports<'foundation-sites/js/foundation.util.triggers'>;
}
declare module 'foundation-sites/vendor/jquery-placeholder/jquery.placeholder.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery-placeholder/jquery.placeholder'>;
}
declare module 'foundation-sites/vendor/jquery.autocomplete/dist/jquery.autocomplete.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery.autocomplete/dist/jquery.autocomplete'>;
}
declare module 'foundation-sites/vendor/jquery.autocomplete/dist/jquery.autocomplete.min.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery.autocomplete/dist/jquery.autocomplete.min'>;
}
declare module 'foundation-sites/vendor/jquery.autocomplete/scripts/countries.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery.autocomplete/scripts/countries'>;
}
declare module 'foundation-sites/vendor/jquery.autocomplete/scripts/demo.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery.autocomplete/scripts/demo'>;
}
declare module 'foundation-sites/vendor/jquery.autocomplete/scripts/jquery-1.8.2.min.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery.autocomplete/scripts/jquery-1.8.2.min'>;
}
declare module 'foundation-sites/vendor/jquery.autocomplete/scripts/jquery.mockjax.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery.autocomplete/scripts/jquery.mockjax'>;
}
declare module 'foundation-sites/vendor/jquery.autocomplete/src/jquery.autocomplete.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery.autocomplete/src/jquery.autocomplete'>;
}
declare module 'foundation-sites/vendor/jquery.cookie/jquery.cookie.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery.cookie/jquery.cookie'>;
}
declare module 'foundation-sites/vendor/jquery/dist/jquery.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/dist/jquery'>;
}
declare module 'foundation-sites/vendor/jquery/dist/jquery.min.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/dist/jquery.min'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax/jsonp.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax/jsonp'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax/load.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax/load'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax/parseJSON.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax/parseJSON'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax/parseXML.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax/parseXML'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax/script.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax/script'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax/var/nonce.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax/var/nonce'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax/var/rquery.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax/var/rquery'>;
}
declare module 'foundation-sites/vendor/jquery/src/ajax/xhr.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/ajax/xhr'>;
}
declare module 'foundation-sites/vendor/jquery/src/attributes.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/attributes'>;
}
declare module 'foundation-sites/vendor/jquery/src/attributes/attr.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/attributes/attr'>;
}
declare module 'foundation-sites/vendor/jquery/src/attributes/classes.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/attributes/classes'>;
}
declare module 'foundation-sites/vendor/jquery/src/attributes/prop.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/attributes/prop'>;
}
declare module 'foundation-sites/vendor/jquery/src/attributes/support.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/attributes/support'>;
}
declare module 'foundation-sites/vendor/jquery/src/attributes/val.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/attributes/val'>;
}
declare module 'foundation-sites/vendor/jquery/src/callbacks.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/callbacks'>;
}
declare module 'foundation-sites/vendor/jquery/src/core.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/core'>;
}
declare module 'foundation-sites/vendor/jquery/src/core/access.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/core/access'>;
}
declare module 'foundation-sites/vendor/jquery/src/core/init.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/core/init'>;
}
declare module 'foundation-sites/vendor/jquery/src/core/parseHTML.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/core/parseHTML'>;
}
declare module 'foundation-sites/vendor/jquery/src/core/ready.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/core/ready'>;
}
declare module 'foundation-sites/vendor/jquery/src/core/var/rsingleTag.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/core/var/rsingleTag'>;
}
declare module 'foundation-sites/vendor/jquery/src/css.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/addGetHookIf.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/addGetHookIf'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/curCSS.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/curCSS'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/defaultDisplay.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/defaultDisplay'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/hiddenVisibleSelectors.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/hiddenVisibleSelectors'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/support.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/support'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/swap.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/swap'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/var/cssExpand.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/var/cssExpand'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/var/getStyles.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/var/getStyles'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/var/isHidden.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/var/isHidden'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/var/rmargin.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/var/rmargin'>;
}
declare module 'foundation-sites/vendor/jquery/src/css/var/rnumnonpx.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/css/var/rnumnonpx'>;
}
declare module 'foundation-sites/vendor/jquery/src/data.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/data'>;
}
declare module 'foundation-sites/vendor/jquery/src/data/accepts.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/data/accepts'>;
}
declare module 'foundation-sites/vendor/jquery/src/data/Data.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/data/Data'>;
}
declare module 'foundation-sites/vendor/jquery/src/data/var/data_priv.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/data/var/data_priv'>;
}
declare module 'foundation-sites/vendor/jquery/src/data/var/data_user.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/data/var/data_user'>;
}
declare module 'foundation-sites/vendor/jquery/src/deferred.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/deferred'>;
}
declare module 'foundation-sites/vendor/jquery/src/deprecated.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/deprecated'>;
}
declare module 'foundation-sites/vendor/jquery/src/dimensions.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/dimensions'>;
}
declare module 'foundation-sites/vendor/jquery/src/effects.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/effects'>;
}
declare module 'foundation-sites/vendor/jquery/src/effects/animatedSelector.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/effects/animatedSelector'>;
}
declare module 'foundation-sites/vendor/jquery/src/effects/Tween.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/effects/Tween'>;
}
declare module 'foundation-sites/vendor/jquery/src/event.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/event'>;
}
declare module 'foundation-sites/vendor/jquery/src/event/ajax.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/event/ajax'>;
}
declare module 'foundation-sites/vendor/jquery/src/event/alias.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/event/alias'>;
}
declare module 'foundation-sites/vendor/jquery/src/event/support.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/event/support'>;
}
declare module 'foundation-sites/vendor/jquery/src/exports/amd.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/exports/amd'>;
}
declare module 'foundation-sites/vendor/jquery/src/exports/global.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/exports/global'>;
}
declare module 'foundation-sites/vendor/jquery/src/intro.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/intro'>;
}
declare module 'foundation-sites/vendor/jquery/src/jquery.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/jquery'>;
}
declare module 'foundation-sites/vendor/jquery/src/manipulation.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/manipulation'>;
}
declare module 'foundation-sites/vendor/jquery/src/manipulation/_evalUrl.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/manipulation/_evalUrl'>;
}
declare module 'foundation-sites/vendor/jquery/src/manipulation/support.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/manipulation/support'>;
}
declare module 'foundation-sites/vendor/jquery/src/manipulation/var/rcheckableType.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/manipulation/var/rcheckableType'>;
}
declare module 'foundation-sites/vendor/jquery/src/offset.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/offset'>;
}
declare module 'foundation-sites/vendor/jquery/src/outro.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/outro'>;
}
declare module 'foundation-sites/vendor/jquery/src/queue.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/queue'>;
}
declare module 'foundation-sites/vendor/jquery/src/queue/delay.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/queue/delay'>;
}
declare module 'foundation-sites/vendor/jquery/src/selector-native.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/selector-native'>;
}
declare module 'foundation-sites/vendor/jquery/src/selector-sizzle.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/selector-sizzle'>;
}
declare module 'foundation-sites/vendor/jquery/src/selector.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/selector'>;
}
declare module 'foundation-sites/vendor/jquery/src/serialize.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/serialize'>;
}
declare module 'foundation-sites/vendor/jquery/src/sizzle/dist/sizzle.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/sizzle/dist/sizzle'>;
}
declare module 'foundation-sites/vendor/jquery/src/sizzle/dist/sizzle.min.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/sizzle/dist/sizzle.min'>;
}
declare module 'foundation-sites/vendor/jquery/src/traversing.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/traversing'>;
}
declare module 'foundation-sites/vendor/jquery/src/traversing/findFilter.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/traversing/findFilter'>;
}
declare module 'foundation-sites/vendor/jquery/src/traversing/var/rneedsContext.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/traversing/var/rneedsContext'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/arr.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/arr'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/class2type.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/class2type'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/concat.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/concat'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/hasOwn.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/hasOwn'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/indexOf.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/indexOf'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/pnum.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/pnum'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/push.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/push'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/rnotwhite.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/rnotwhite'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/slice.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/slice'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/strundefined.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/strundefined'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/support.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/support'>;
}
declare module 'foundation-sites/vendor/jquery/src/var/toString.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/var/toString'>;
}
declare module 'foundation-sites/vendor/jquery/src/wrap.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/jquery/src/wrap'>;
}
declare module 'foundation-sites/vendor/lodash/dist/lodash.compat.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/lodash/dist/lodash.compat'>;
}
declare module 'foundation-sites/vendor/lodash/dist/lodash.compat.min.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/lodash/dist/lodash.compat.min'>;
}
declare module 'foundation-sites/vendor/lodash/dist/lodash.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/lodash/dist/lodash'>;
}
declare module 'foundation-sites/vendor/lodash/dist/lodash.min.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/lodash/dist/lodash.min'>;
}
declare module 'foundation-sites/vendor/lodash/dist/lodash.underscore.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/lodash/dist/lodash.underscore'>;
}
declare module 'foundation-sites/vendor/lodash/dist/lodash.underscore.min.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/lodash/dist/lodash.underscore.min'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/a-download.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/a-download'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/audio-audiodata-api.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/audio-audiodata-api'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/audio-webaudio-api.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/audio-webaudio-api'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/battery-api.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/battery-api'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/battery-level.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/battery-level'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/blob-constructor.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/blob-constructor'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/canvas-todataurl-type.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/canvas-todataurl-type'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/contenteditable.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/contenteditable'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/contentsecuritypolicy.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/contentsecuritypolicy'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/contextmenu.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/contextmenu'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/cookies.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/cookies'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/cors.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/cors'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-backgroundposition-shorthand.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-backgroundposition-shorthand'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-backgroundposition-xy.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-backgroundposition-xy'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-backgroundrepeat.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-backgroundrepeat'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-backgroundsizecover.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-backgroundsizecover'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-boxsizing.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-boxsizing'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-calc.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-calc'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-cubicbezierrange.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-cubicbezierrange'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-displayrunin.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-displayrunin'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-displaytable.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-displaytable'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-filters.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-filters'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-hyphens.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-hyphens'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-lastchild.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-lastchild'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-mask.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-mask'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-mediaqueries.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-mediaqueries'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-objectfit.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-objectfit'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-overflow-scrolling.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-overflow-scrolling'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-pointerevents.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-pointerevents'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-positionsticky.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-positionsticky'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-regions.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-regions'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-remunit.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-remunit'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-resize.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-resize'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-scrollbars.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-scrollbars'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-shapes.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-shapes'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-subpixelfont.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-subpixelfont'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-supports.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-supports'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-userselect.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-userselect'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-vhunit.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-vhunit'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-vmaxunit.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-vmaxunit'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-vminunit.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-vminunit'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/css-vwunit.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/css-vwunit'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/custom-protocol-handler.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/custom-protocol-handler'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/dart.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/dart'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/dataview-api.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/dataview-api'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/dom-classlist.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/dom-classlist'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/dom-createElement-attrs.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/dom-createElement-attrs'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/dom-dataset.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/dom-dataset'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/dom-microdata.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/dom-microdata'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-datalist.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/elem-datalist'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-details.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/elem-details'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-output.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/elem-output'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-progress-meter.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/elem-progress-meter'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-ruby.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/elem-ruby'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-time.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/elem-time'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/elem-track.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/elem-track'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/emoji.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/emoji'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/es5-strictmode.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/es5-strictmode'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/event-deviceorientation-motion.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/event-deviceorientation-motion'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/exif-orientation.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/exif-orientation'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/file-api.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/file-api'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/file-filesystem.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/file-filesystem'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-fileinput.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/forms-fileinput'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-formattribute.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/forms-formattribute'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-inputnumber-l10n.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/forms-inputnumber-l10n'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-placeholder.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/forms-placeholder'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-speechinput.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/forms-speechinput'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/forms-validation.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/forms-validation'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/fullscreen-api.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/fullscreen-api'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/gamepad.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/gamepad'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/getusermedia.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/getusermedia'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/ie8compat.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/ie8compat'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/iframe-sandbox.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/iframe-sandbox'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/iframe-seamless.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/iframe-seamless'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/iframe-srcdoc.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/iframe-srcdoc'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/img-apng.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/img-apng'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/img-webp.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/img-webp'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/json.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/json'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/lists-reversed.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/lists-reversed'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/mathml.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/mathml'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/network-connection.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/network-connection'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/network-eventsource.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/network-eventsource'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/network-xhr2.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/network-xhr2'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/notification.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/notification'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/performance.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/performance'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/pointerlock-api.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/pointerlock-api'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/quota-management-api.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/quota-management-api'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/requestanimationframe.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/requestanimationframe'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/script-async.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/script-async'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/script-defer.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/script-defer'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/style-scoped.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/style-scoped'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/svg-filters.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/svg-filters'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/unicode.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/unicode'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/url-data-uri.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/url-data-uri'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/userdata.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/userdata'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/vibration.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/vibration'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/web-intents.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/web-intents'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/webgl-extensions.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/webgl-extensions'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/websockets-binary.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/websockets-binary'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/window-framed.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/window-framed'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/workers-blobworkers.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/workers-blobworkers'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/workers-dataworkers.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/workers-dataworkers'>;
}
declare module 'foundation-sites/vendor/modernizr/feature-detects/workers-sharedworkers.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/feature-detects/workers-sharedworkers'>;
}
declare module 'foundation-sites/vendor/modernizr/grunt.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/grunt'>;
}
declare module 'foundation-sites/vendor/modernizr/modernizr.js' {
  declare module.exports: $Exports<'foundation-sites/vendor/modernizr/modernizr'>;
}
