// flow-typed signature: 2fc76737aa5f248714dfe83b7a9da208
// flow-typed version: <<STUB>>/functional-components_v0.0.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'functional-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'functional-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'functional-components/dist/index' {
  declare module.exports: any;
}

declare module 'functional-components/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'functional-components/dist/index.js' {
  declare module.exports: $Exports<'functional-components/dist/index'>;
}
declare module 'functional-components/webpack.config.js' {
  declare module.exports: $Exports<'functional-components/webpack.config'>;
}
