// flow-typed signature: 03a707a8fc3578e5260cf5bb58fc0ffb
// flow-typed version: <<STUB>>/history_v^1.14.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'history' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'history/es6/Actions' {
  declare module.exports: any;
}

declare module 'history/es6/AsyncUtils' {
  declare module.exports: any;
}

declare module 'history/es6/createBrowserHistory' {
  declare module.exports: any;
}

declare module 'history/es6/createDOMHistory' {
  declare module.exports: any;
}

declare module 'history/es6/createHashHistory' {
  declare module.exports: any;
}

declare module 'history/es6/createHistory' {
  declare module.exports: any;
}

declare module 'history/es6/createLocation' {
  declare module.exports: any;
}

declare module 'history/es6/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'history/es6/deprecate' {
  declare module.exports: any;
}

declare module 'history/es6/DOMStateStorage' {
  declare module.exports: any;
}

declare module 'history/es6/DOMUtils' {
  declare module.exports: any;
}

declare module 'history/es6/enableBeforeUnload' {
  declare module.exports: any;
}

declare module 'history/es6/enableQueries' {
  declare module.exports: any;
}

declare module 'history/es6/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'history/es6/extractPath' {
  declare module.exports: any;
}

declare module 'history/es6/index' {
  declare module.exports: any;
}

declare module 'history/es6/parsePath' {
  declare module.exports: any;
}

declare module 'history/es6/runTransitionHook' {
  declare module.exports: any;
}

declare module 'history/es6/useBasename' {
  declare module.exports: any;
}

declare module 'history/es6/useBeforeUnload' {
  declare module.exports: any;
}

declare module 'history/es6/useQueries' {
  declare module.exports: any;
}

declare module 'history/lib/Actions' {
  declare module.exports: any;
}

declare module 'history/lib/AsyncUtils' {
  declare module.exports: any;
}

declare module 'history/lib/createBrowserHistory' {
  declare module.exports: any;
}

declare module 'history/lib/createDOMHistory' {
  declare module.exports: any;
}

declare module 'history/lib/createHashHistory' {
  declare module.exports: any;
}

declare module 'history/lib/createHistory' {
  declare module.exports: any;
}

declare module 'history/lib/createLocation' {
  declare module.exports: any;
}

declare module 'history/lib/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'history/lib/deprecate' {
  declare module.exports: any;
}

declare module 'history/lib/DOMStateStorage' {
  declare module.exports: any;
}

declare module 'history/lib/DOMUtils' {
  declare module.exports: any;
}

declare module 'history/lib/enableBeforeUnload' {
  declare module.exports: any;
}

declare module 'history/lib/enableQueries' {
  declare module.exports: any;
}

declare module 'history/lib/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'history/lib/extractPath' {
  declare module.exports: any;
}

declare module 'history/lib/index' {
  declare module.exports: any;
}

declare module 'history/lib/parsePath' {
  declare module.exports: any;
}

declare module 'history/lib/runTransitionHook' {
  declare module.exports: any;
}

declare module 'history/lib/useBasename' {
  declare module.exports: any;
}

declare module 'history/lib/useBeforeUnload' {
  declare module.exports: any;
}

declare module 'history/lib/useQueries' {
  declare module.exports: any;
}

declare module 'history/npm-scripts/postinstall' {
  declare module.exports: any;
}

declare module 'history/umd/History' {
  declare module.exports: any;
}

declare module 'history/umd/History.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'history/es6/Actions.js' {
  declare module.exports: $Exports<'history/es6/Actions'>;
}
declare module 'history/es6/AsyncUtils.js' {
  declare module.exports: $Exports<'history/es6/AsyncUtils'>;
}
declare module 'history/es6/createBrowserHistory.js' {
  declare module.exports: $Exports<'history/es6/createBrowserHistory'>;
}
declare module 'history/es6/createDOMHistory.js' {
  declare module.exports: $Exports<'history/es6/createDOMHistory'>;
}
declare module 'history/es6/createHashHistory.js' {
  declare module.exports: $Exports<'history/es6/createHashHistory'>;
}
declare module 'history/es6/createHistory.js' {
  declare module.exports: $Exports<'history/es6/createHistory'>;
}
declare module 'history/es6/createLocation.js' {
  declare module.exports: $Exports<'history/es6/createLocation'>;
}
declare module 'history/es6/createMemoryHistory.js' {
  declare module.exports: $Exports<'history/es6/createMemoryHistory'>;
}
declare module 'history/es6/deprecate.js' {
  declare module.exports: $Exports<'history/es6/deprecate'>;
}
declare module 'history/es6/DOMStateStorage.js' {
  declare module.exports: $Exports<'history/es6/DOMStateStorage'>;
}
declare module 'history/es6/DOMUtils.js' {
  declare module.exports: $Exports<'history/es6/DOMUtils'>;
}
declare module 'history/es6/enableBeforeUnload.js' {
  declare module.exports: $Exports<'history/es6/enableBeforeUnload'>;
}
declare module 'history/es6/enableQueries.js' {
  declare module.exports: $Exports<'history/es6/enableQueries'>;
}
declare module 'history/es6/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'history/es6/ExecutionEnvironment'>;
}
declare module 'history/es6/extractPath.js' {
  declare module.exports: $Exports<'history/es6/extractPath'>;
}
declare module 'history/es6/index.js' {
  declare module.exports: $Exports<'history/es6/index'>;
}
declare module 'history/es6/parsePath.js' {
  declare module.exports: $Exports<'history/es6/parsePath'>;
}
declare module 'history/es6/runTransitionHook.js' {
  declare module.exports: $Exports<'history/es6/runTransitionHook'>;
}
declare module 'history/es6/useBasename.js' {
  declare module.exports: $Exports<'history/es6/useBasename'>;
}
declare module 'history/es6/useBeforeUnload.js' {
  declare module.exports: $Exports<'history/es6/useBeforeUnload'>;
}
declare module 'history/es6/useQueries.js' {
  declare module.exports: $Exports<'history/es6/useQueries'>;
}
declare module 'history/lib/Actions.js' {
  declare module.exports: $Exports<'history/lib/Actions'>;
}
declare module 'history/lib/AsyncUtils.js' {
  declare module.exports: $Exports<'history/lib/AsyncUtils'>;
}
declare module 'history/lib/createBrowserHistory.js' {
  declare module.exports: $Exports<'history/lib/createBrowserHistory'>;
}
declare module 'history/lib/createDOMHistory.js' {
  declare module.exports: $Exports<'history/lib/createDOMHistory'>;
}
declare module 'history/lib/createHashHistory.js' {
  declare module.exports: $Exports<'history/lib/createHashHistory'>;
}
declare module 'history/lib/createHistory.js' {
  declare module.exports: $Exports<'history/lib/createHistory'>;
}
declare module 'history/lib/createLocation.js' {
  declare module.exports: $Exports<'history/lib/createLocation'>;
}
declare module 'history/lib/createMemoryHistory.js' {
  declare module.exports: $Exports<'history/lib/createMemoryHistory'>;
}
declare module 'history/lib/deprecate.js' {
  declare module.exports: $Exports<'history/lib/deprecate'>;
}
declare module 'history/lib/DOMStateStorage.js' {
  declare module.exports: $Exports<'history/lib/DOMStateStorage'>;
}
declare module 'history/lib/DOMUtils.js' {
  declare module.exports: $Exports<'history/lib/DOMUtils'>;
}
declare module 'history/lib/enableBeforeUnload.js' {
  declare module.exports: $Exports<'history/lib/enableBeforeUnload'>;
}
declare module 'history/lib/enableQueries.js' {
  declare module.exports: $Exports<'history/lib/enableQueries'>;
}
declare module 'history/lib/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'history/lib/ExecutionEnvironment'>;
}
declare module 'history/lib/extractPath.js' {
  declare module.exports: $Exports<'history/lib/extractPath'>;
}
declare module 'history/lib/index.js' {
  declare module.exports: $Exports<'history/lib/index'>;
}
declare module 'history/lib/parsePath.js' {
  declare module.exports: $Exports<'history/lib/parsePath'>;
}
declare module 'history/lib/runTransitionHook.js' {
  declare module.exports: $Exports<'history/lib/runTransitionHook'>;
}
declare module 'history/lib/useBasename.js' {
  declare module.exports: $Exports<'history/lib/useBasename'>;
}
declare module 'history/lib/useBeforeUnload.js' {
  declare module.exports: $Exports<'history/lib/useBeforeUnload'>;
}
declare module 'history/lib/useQueries.js' {
  declare module.exports: $Exports<'history/lib/useQueries'>;
}
declare module 'history/npm-scripts/postinstall.js' {
  declare module.exports: $Exports<'history/npm-scripts/postinstall'>;
}
declare module 'history/umd/History.js' {
  declare module.exports: $Exports<'history/umd/History'>;
}
declare module 'history/umd/History.min.js' {
  declare module.exports: $Exports<'history/umd/History.min'>;
}
