// flow-typed signature: 502361bf61e4771e3872b57697109769
// flow-typed version: <<STUB>>/jest-webpack-alias_v^3.3.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-webpack-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-webpack-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-webpack-alias/lib/cacheize' {
  declare module.exports: any;
}

declare module 'jest-webpack-alias/lib/dirHas' {
  declare module.exports: any;
}

declare module 'jest-webpack-alias/lib/preprocessor' {
  declare module.exports: any;
}

declare module 'jest-webpack-alias/lib/stringOrArray' {
  declare module.exports: any;
}

declare module 'jest-webpack-alias/lib/webpackInfo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-webpack-alias/lib/cacheize.js' {
  declare module.exports: $Exports<'jest-webpack-alias/lib/cacheize'>;
}
declare module 'jest-webpack-alias/lib/dirHas.js' {
  declare module.exports: $Exports<'jest-webpack-alias/lib/dirHas'>;
}
declare module 'jest-webpack-alias/lib/preprocessor.js' {
  declare module.exports: $Exports<'jest-webpack-alias/lib/preprocessor'>;
}
declare module 'jest-webpack-alias/lib/stringOrArray.js' {
  declare module.exports: $Exports<'jest-webpack-alias/lib/stringOrArray'>;
}
declare module 'jest-webpack-alias/lib/webpackInfo.js' {
  declare module.exports: $Exports<'jest-webpack-alias/lib/webpackInfo'>;
}
