// flow-typed signature: aa67c93c3ac6edf5e4757e1de0c2fd41
// flow-typed version: <<STUB>>/markdown-loader_v^0.1.7/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'markdown-loader/index' {
  declare module.exports: $Exports<'markdown-loader'>;
}
declare module 'markdown-loader/index.js' {
  declare module.exports: $Exports<'markdown-loader'>;
}
