// flow-typed signature: 8176db2f37d35a7bfdefca1e9f522bdf
// flow-typed version: <<STUB>>/node-ensure_v0.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-ensure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-ensure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-ensure/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-ensure/browser.js' {
  declare module.exports: $Exports<'node-ensure/browser'>;
}
declare module 'node-ensure/index' {
  declare module.exports: $Exports<'node-ensure'>;
}
declare module 'node-ensure/index.js' {
  declare module.exports: $Exports<'node-ensure'>;
}
