// flow-typed signature: 54ae201f1fcb99bcc10ce10e987007fc
// flow-typed version: <<STUB>>/npm-install-webpack-plugin_v^4.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-install-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-install-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-install-webpack-plugin/src/installer' {
  declare module.exports: any;
}

declare module 'npm-install-webpack-plugin/src/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-install-webpack-plugin/index' {
  declare module.exports: $Exports<'npm-install-webpack-plugin'>;
}
declare module 'npm-install-webpack-plugin/index.js' {
  declare module.exports: $Exports<'npm-install-webpack-plugin'>;
}
declare module 'npm-install-webpack-plugin/src/installer.js' {
  declare module.exports: $Exports<'npm-install-webpack-plugin/src/installer'>;
}
declare module 'npm-install-webpack-plugin/src/plugin.js' {
  declare module.exports: $Exports<'npm-install-webpack-plugin/src/plugin'>;
}
