// flow-typed signature: 5e18f731affe73e4e508e0081d1143d9
// flow-typed version: <<STUB>>/plop_v1.5.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'plop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plop/example/plopfile' {
  declare module.exports: any;
}

declare module 'plop/mod/console-out' {
  declare module.exports: any;
}

declare module 'plop/mod/fs-promise' {
  declare module.exports: any;
}

declare module 'plop/mod/logic' {
  declare module.exports: any;
}

declare module 'plop/mod/plop-base' {
  declare module.exports: any;
}

declare module 'plop/plop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plop/example/plopfile.js' {
  declare module.exports: $Exports<'plop/example/plopfile'>;
}
declare module 'plop/mod/console-out.js' {
  declare module.exports: $Exports<'plop/mod/console-out'>;
}
declare module 'plop/mod/fs-promise.js' {
  declare module.exports: $Exports<'plop/mod/fs-promise'>;
}
declare module 'plop/mod/logic.js' {
  declare module.exports: $Exports<'plop/mod/logic'>;
}
declare module 'plop/mod/plop-base.js' {
  declare module.exports: $Exports<'plop/mod/plop-base'>;
}
declare module 'plop/plop.js' {
  declare module.exports: $Exports<'plop/plop'>;
}
