// flow-typed signature: b28ded0120bd4c6188758805b91285a4
// flow-typed version: <<STUB>>/react-apollo_v^0.5.13/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apollo/ApolloProvider' {
  declare module.exports: any;
}

declare module 'react-apollo/dist/index' {
  declare module.exports: any;
}

declare module 'react-apollo/dist/index.min' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/meteor/client/index' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/meteor/imports/App' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/meteor/imports/Pokemon' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/meteor/server/index' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/react-native/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/react-native/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/react-native/index.ios' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/react-native/Pokemon' {
  declare module.exports: any;
}

declare module 'react-apollo/graphql' {
  declare module.exports: any;
}

declare module 'react-apollo/parser' {
  declare module.exports: any;
}

declare module 'react-apollo/preprocessor' {
  declare module.exports: any;
}

declare module 'react-apollo/scripts/filesize' {
  declare module.exports: any;
}

declare module 'react-apollo/server' {
  declare module.exports: any;
}

declare module 'react-apollo/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-apollo/test-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apollo/ApolloProvider.js' {
  declare module.exports: $Exports<'react-apollo/ApolloProvider'>;
}
declare module 'react-apollo/dist/index.js' {
  declare module.exports: $Exports<'react-apollo/dist/index'>;
}
declare module 'react-apollo/dist/index.min.js' {
  declare module.exports: $Exports<'react-apollo/dist/index.min'>;
}
declare module 'react-apollo/examples/meteor/client/index.js' {
  declare module.exports: $Exports<'react-apollo/examples/meteor/client/index'>;
}
declare module 'react-apollo/examples/meteor/imports/App.js' {
  declare module.exports: $Exports<'react-apollo/examples/meteor/imports/App'>;
}
declare module 'react-apollo/examples/meteor/imports/Pokemon.js' {
  declare module.exports: $Exports<'react-apollo/examples/meteor/imports/Pokemon'>;
}
declare module 'react-apollo/examples/meteor/server/index.js' {
  declare module.exports: $Exports<'react-apollo/examples/meteor/server/index'>;
}
declare module 'react-apollo/examples/react-native/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-apollo/examples/react-native/__tests__/index.android'>;
}
declare module 'react-apollo/examples/react-native/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-apollo/examples/react-native/__tests__/index.ios'>;
}
declare module 'react-apollo/examples/react-native/index.ios.js' {
  declare module.exports: $Exports<'react-apollo/examples/react-native/index.ios'>;
}
declare module 'react-apollo/examples/react-native/Pokemon.js' {
  declare module.exports: $Exports<'react-apollo/examples/react-native/Pokemon'>;
}
declare module 'react-apollo/graphql.js' {
  declare module.exports: $Exports<'react-apollo/graphql'>;
}
declare module 'react-apollo/index' {
  declare module.exports: $Exports<'react-apollo'>;
}
declare module 'react-apollo/index.js' {
  declare module.exports: $Exports<'react-apollo'>;
}
declare module 'react-apollo/parser.js' {
  declare module.exports: $Exports<'react-apollo/parser'>;
}
declare module 'react-apollo/preprocessor.js' {
  declare module.exports: $Exports<'react-apollo/preprocessor'>;
}
declare module 'react-apollo/scripts/filesize.js' {
  declare module.exports: $Exports<'react-apollo/scripts/filesize'>;
}
declare module 'react-apollo/server.js' {
  declare module.exports: $Exports<'react-apollo/server'>;
}
declare module 'react-apollo/shallowEqual.js' {
  declare module.exports: $Exports<'react-apollo/shallowEqual'>;
}
declare module 'react-apollo/test-utils.js' {
  declare module.exports: $Exports<'react-apollo/test-utils'>;
}
