// flow-typed signature: 59915e776ba70fa7165c510c7f4b57b9
// flow-typed version: <<STUB>>/redux-auth-wrapper_v^0.8.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-auth-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-auth-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-auth-wrapper/lib/index' {
  declare module.exports: any;
}

declare module 'redux-auth-wrapper/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-auth-wrapper/lib/index.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/lib/index'>;
}
declare module 'redux-auth-wrapper/src/index.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/src/index'>;
}
