// flow-typed signature: 69fc73801bb4d67ce1bcb84f82c254a1
// flow-typed version: <<STUB>>/redux-mock-store_v^1.1.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-mock-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-mock-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-mock-store/lib/index' {
  declare module.exports: any;
}

declare module 'redux-mock-store/test/index' {
  declare module.exports: any;
}

declare module 'redux-mock-store/test/mock/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-mock-store/lib/index.js' {
  declare module.exports: $Exports<'redux-mock-store/lib/index'>;
}
declare module 'redux-mock-store/test/index.js' {
  declare module.exports: $Exports<'redux-mock-store/test/index'>;
}
declare module 'redux-mock-store/test/mock/middleware.js' {
  declare module.exports: $Exports<'redux-mock-store/test/mock/middleware'>;
}
