// flow-typed signature: 0d46428952b3edfbf745646379da5161
// flow-typed version: <<STUB>>/utils_v^0.3.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utils/lib/array/after' {
  declare module.exports: any;
}

declare module 'utils/lib/array/arrayify' {
  declare module.exports: any;
}

declare module 'utils/lib/array/before' {
  declare module.exports: any;
}

declare module 'utils/lib/array/compact' {
  declare module.exports: any;
}

declare module 'utils/lib/array/difference' {
  declare module.exports: any;
}

declare module 'utils/lib/array/each' {
  declare module.exports: any;
}

declare module 'utils/lib/array/first' {
  declare module.exports: any;
}

declare module 'utils/lib/array/flatten' {
  declare module.exports: any;
}

declare module 'utils/lib/array/forEach' {
  declare module.exports: any;
}

declare module 'utils/lib/array/index' {
  declare module.exports: any;
}

declare module 'utils/lib/array/indexOf' {
  declare module.exports: any;
}

declare module 'utils/lib/array/isArray' {
  declare module.exports: any;
}

declare module 'utils/lib/array/last' {
  declare module.exports: any;
}

declare module 'utils/lib/array/map' {
  declare module.exports: any;
}

declare module 'utils/lib/array/slice' {
  declare module.exports: any;
}

declare module 'utils/lib/array/sort' {
  declare module.exports: any;
}

declare module 'utils/lib/array/union' {
  declare module.exports: any;
}

declare module 'utils/lib/array/unique' {
  declare module.exports: any;
}

declare module 'utils/lib/collection/any' {
  declare module.exports: any;
}

declare module 'utils/lib/collection/contains' {
  declare module.exports: any;
}

declare module 'utils/lib/collection/index' {
  declare module.exports: any;
}

declare module 'utils/lib/fs/index' {
  declare module.exports: any;
}

declare module 'utils/lib/fs/tryRead' {
  declare module.exports: any;
}

declare module 'utils/lib/fs/tryReaddir' {
  declare module.exports: any;
}

declare module 'utils/lib/fs/tryRequire' {
  declare module.exports: any;
}

declare module 'utils/lib/function/identity' {
  declare module.exports: any;
}

declare module 'utils/lib/function/index' {
  declare module.exports: any;
}

declare module 'utils/lib/function/noop' {
  declare module.exports: any;
}

declare module 'utils/lib/function/partialRight' {
  declare module.exports: any;
}

declare module 'utils/lib/index' {
  declare module.exports: any;
}

declare module 'utils/lib/lang/hasValues' {
  declare module.exports: any;
}

declare module 'utils/lib/lang/index' {
  declare module.exports: any;
}

declare module 'utils/lib/lang/isEmpty' {
  declare module.exports: any;
}

declare module 'utils/lib/lang/isObject' {
  declare module.exports: any;
}

declare module 'utils/lib/lang/isPlainObject' {
  declare module.exports: any;
}

declare module 'utils/lib/lang/typeOf' {
  declare module.exports: any;
}

declare module 'utils/lib/math/index' {
  declare module.exports: any;
}

declare module 'utils/lib/math/sum' {
  declare module.exports: any;
}

declare module 'utils/lib/object/defaults' {
  declare module.exports: any;
}

declare module 'utils/lib/object/extend' {
  declare module.exports: any;
}

declare module 'utils/lib/object/filter' {
  declare module.exports: any;
}

declare module 'utils/lib/object/forIn' {
  declare module.exports: any;
}

declare module 'utils/lib/object/forOwn' {
  declare module.exports: any;
}

declare module 'utils/lib/object/functions' {
  declare module.exports: any;
}

declare module 'utils/lib/object/hasOwn' {
  declare module.exports: any;
}

declare module 'utils/lib/object/index' {
  declare module.exports: any;
}

declare module 'utils/lib/object/keys' {
  declare module.exports: any;
}

declare module 'utils/lib/object/mapValues' {
  declare module.exports: any;
}

declare module 'utils/lib/object/merge' {
  declare module.exports: any;
}

declare module 'utils/lib/object/methods' {
  declare module.exports: any;
}

declare module 'utils/lib/object/omit' {
  declare module.exports: any;
}

declare module 'utils/lib/object/pick' {
  declare module.exports: any;
}

declare module 'utils/lib/object/pluck' {
  declare module.exports: any;
}

declare module 'utils/lib/object/prop' {
  declare module.exports: any;
}

declare module 'utils/lib/object/reduce' {
  declare module.exports: any;
}

declare module 'utils/lib/object/result' {
  declare module.exports: any;
}

declare module 'utils/lib/object/some' {
  declare module.exports: any;
}

declare module 'utils/lib/string/camelcase' {
  declare module.exports: any;
}

declare module 'utils/lib/string/centerAlign' {
  declare module.exports: any;
}

declare module 'utils/lib/string/chop' {
  declare module.exports: any;
}

declare module 'utils/lib/string/count' {
  declare module.exports: any;
}

declare module 'utils/lib/string/dashcase' {
  declare module.exports: any;
}

declare module 'utils/lib/string/dotcase' {
  declare module.exports: any;
}

declare module 'utils/lib/string/ellipsis' {
  declare module.exports: any;
}

declare module 'utils/lib/string/hyphenate' {
  declare module.exports: any;
}

declare module 'utils/lib/string/index' {
  declare module.exports: any;
}

declare module 'utils/lib/string/isString' {
  declare module.exports: any;
}

declare module 'utils/lib/string/pascalcase' {
  declare module.exports: any;
}

declare module 'utils/lib/string/pathcase' {
  declare module.exports: any;
}

declare module 'utils/lib/string/replace' {
  declare module.exports: any;
}

declare module 'utils/lib/string/reverse' {
  declare module.exports: any;
}

declare module 'utils/lib/string/rightAlign' {
  declare module.exports: any;
}

declare module 'utils/lib/string/sentencecase' {
  declare module.exports: any;
}

declare module 'utils/lib/string/slugify' {
  declare module.exports: any;
}

declare module 'utils/lib/string/snakecase' {
  declare module.exports: any;
}

declare module 'utils/lib/string/toString' {
  declare module.exports: any;
}

declare module 'utils/lib/string/truncate' {
  declare module.exports: any;
}

declare module 'utils/lib/string/wordwrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utils/index' {
  declare module.exports: $Exports<'utils'>;
}
declare module 'utils/index.js' {
  declare module.exports: $Exports<'utils'>;
}
declare module 'utils/lib/array/after.js' {
  declare module.exports: $Exports<'utils/lib/array/after'>;
}
declare module 'utils/lib/array/arrayify.js' {
  declare module.exports: $Exports<'utils/lib/array/arrayify'>;
}
declare module 'utils/lib/array/before.js' {
  declare module.exports: $Exports<'utils/lib/array/before'>;
}
declare module 'utils/lib/array/compact.js' {
  declare module.exports: $Exports<'utils/lib/array/compact'>;
}
declare module 'utils/lib/array/difference.js' {
  declare module.exports: $Exports<'utils/lib/array/difference'>;
}
declare module 'utils/lib/array/each.js' {
  declare module.exports: $Exports<'utils/lib/array/each'>;
}
declare module 'utils/lib/array/first.js' {
  declare module.exports: $Exports<'utils/lib/array/first'>;
}
declare module 'utils/lib/array/flatten.js' {
  declare module.exports: $Exports<'utils/lib/array/flatten'>;
}
declare module 'utils/lib/array/forEach.js' {
  declare module.exports: $Exports<'utils/lib/array/forEach'>;
}
declare module 'utils/lib/array/index.js' {
  declare module.exports: $Exports<'utils/lib/array/index'>;
}
declare module 'utils/lib/array/indexOf.js' {
  declare module.exports: $Exports<'utils/lib/array/indexOf'>;
}
declare module 'utils/lib/array/isArray.js' {
  declare module.exports: $Exports<'utils/lib/array/isArray'>;
}
declare module 'utils/lib/array/last.js' {
  declare module.exports: $Exports<'utils/lib/array/last'>;
}
declare module 'utils/lib/array/map.js' {
  declare module.exports: $Exports<'utils/lib/array/map'>;
}
declare module 'utils/lib/array/slice.js' {
  declare module.exports: $Exports<'utils/lib/array/slice'>;
}
declare module 'utils/lib/array/sort.js' {
  declare module.exports: $Exports<'utils/lib/array/sort'>;
}
declare module 'utils/lib/array/union.js' {
  declare module.exports: $Exports<'utils/lib/array/union'>;
}
declare module 'utils/lib/array/unique.js' {
  declare module.exports: $Exports<'utils/lib/array/unique'>;
}
declare module 'utils/lib/collection/any.js' {
  declare module.exports: $Exports<'utils/lib/collection/any'>;
}
declare module 'utils/lib/collection/contains.js' {
  declare module.exports: $Exports<'utils/lib/collection/contains'>;
}
declare module 'utils/lib/collection/index.js' {
  declare module.exports: $Exports<'utils/lib/collection/index'>;
}
declare module 'utils/lib/fs/index.js' {
  declare module.exports: $Exports<'utils/lib/fs/index'>;
}
declare module 'utils/lib/fs/tryRead.js' {
  declare module.exports: $Exports<'utils/lib/fs/tryRead'>;
}
declare module 'utils/lib/fs/tryReaddir.js' {
  declare module.exports: $Exports<'utils/lib/fs/tryReaddir'>;
}
declare module 'utils/lib/fs/tryRequire.js' {
  declare module.exports: $Exports<'utils/lib/fs/tryRequire'>;
}
declare module 'utils/lib/function/identity.js' {
  declare module.exports: $Exports<'utils/lib/function/identity'>;
}
declare module 'utils/lib/function/index.js' {
  declare module.exports: $Exports<'utils/lib/function/index'>;
}
declare module 'utils/lib/function/noop.js' {
  declare module.exports: $Exports<'utils/lib/function/noop'>;
}
declare module 'utils/lib/function/partialRight.js' {
  declare module.exports: $Exports<'utils/lib/function/partialRight'>;
}
declare module 'utils/lib/index.js' {
  declare module.exports: $Exports<'utils/lib/index'>;
}
declare module 'utils/lib/lang/hasValues.js' {
  declare module.exports: $Exports<'utils/lib/lang/hasValues'>;
}
declare module 'utils/lib/lang/index.js' {
  declare module.exports: $Exports<'utils/lib/lang/index'>;
}
declare module 'utils/lib/lang/isEmpty.js' {
  declare module.exports: $Exports<'utils/lib/lang/isEmpty'>;
}
declare module 'utils/lib/lang/isObject.js' {
  declare module.exports: $Exports<'utils/lib/lang/isObject'>;
}
declare module 'utils/lib/lang/isPlainObject.js' {
  declare module.exports: $Exports<'utils/lib/lang/isPlainObject'>;
}
declare module 'utils/lib/lang/typeOf.js' {
  declare module.exports: $Exports<'utils/lib/lang/typeOf'>;
}
declare module 'utils/lib/math/index.js' {
  declare module.exports: $Exports<'utils/lib/math/index'>;
}
declare module 'utils/lib/math/sum.js' {
  declare module.exports: $Exports<'utils/lib/math/sum'>;
}
declare module 'utils/lib/object/defaults.js' {
  declare module.exports: $Exports<'utils/lib/object/defaults'>;
}
declare module 'utils/lib/object/extend.js' {
  declare module.exports: $Exports<'utils/lib/object/extend'>;
}
declare module 'utils/lib/object/filter.js' {
  declare module.exports: $Exports<'utils/lib/object/filter'>;
}
declare module 'utils/lib/object/forIn.js' {
  declare module.exports: $Exports<'utils/lib/object/forIn'>;
}
declare module 'utils/lib/object/forOwn.js' {
  declare module.exports: $Exports<'utils/lib/object/forOwn'>;
}
declare module 'utils/lib/object/functions.js' {
  declare module.exports: $Exports<'utils/lib/object/functions'>;
}
declare module 'utils/lib/object/hasOwn.js' {
  declare module.exports: $Exports<'utils/lib/object/hasOwn'>;
}
declare module 'utils/lib/object/index.js' {
  declare module.exports: $Exports<'utils/lib/object/index'>;
}
declare module 'utils/lib/object/keys.js' {
  declare module.exports: $Exports<'utils/lib/object/keys'>;
}
declare module 'utils/lib/object/mapValues.js' {
  declare module.exports: $Exports<'utils/lib/object/mapValues'>;
}
declare module 'utils/lib/object/merge.js' {
  declare module.exports: $Exports<'utils/lib/object/merge'>;
}
declare module 'utils/lib/object/methods.js' {
  declare module.exports: $Exports<'utils/lib/object/methods'>;
}
declare module 'utils/lib/object/omit.js' {
  declare module.exports: $Exports<'utils/lib/object/omit'>;
}
declare module 'utils/lib/object/pick.js' {
  declare module.exports: $Exports<'utils/lib/object/pick'>;
}
declare module 'utils/lib/object/pluck.js' {
  declare module.exports: $Exports<'utils/lib/object/pluck'>;
}
declare module 'utils/lib/object/prop.js' {
  declare module.exports: $Exports<'utils/lib/object/prop'>;
}
declare module 'utils/lib/object/reduce.js' {
  declare module.exports: $Exports<'utils/lib/object/reduce'>;
}
declare module 'utils/lib/object/result.js' {
  declare module.exports: $Exports<'utils/lib/object/result'>;
}
declare module 'utils/lib/object/some.js' {
  declare module.exports: $Exports<'utils/lib/object/some'>;
}
declare module 'utils/lib/string/camelcase.js' {
  declare module.exports: $Exports<'utils/lib/string/camelcase'>;
}
declare module 'utils/lib/string/centerAlign.js' {
  declare module.exports: $Exports<'utils/lib/string/centerAlign'>;
}
declare module 'utils/lib/string/chop.js' {
  declare module.exports: $Exports<'utils/lib/string/chop'>;
}
declare module 'utils/lib/string/count.js' {
  declare module.exports: $Exports<'utils/lib/string/count'>;
}
declare module 'utils/lib/string/dashcase.js' {
  declare module.exports: $Exports<'utils/lib/string/dashcase'>;
}
declare module 'utils/lib/string/dotcase.js' {
  declare module.exports: $Exports<'utils/lib/string/dotcase'>;
}
declare module 'utils/lib/string/ellipsis.js' {
  declare module.exports: $Exports<'utils/lib/string/ellipsis'>;
}
declare module 'utils/lib/string/hyphenate.js' {
  declare module.exports: $Exports<'utils/lib/string/hyphenate'>;
}
declare module 'utils/lib/string/index.js' {
  declare module.exports: $Exports<'utils/lib/string/index'>;
}
declare module 'utils/lib/string/isString.js' {
  declare module.exports: $Exports<'utils/lib/string/isString'>;
}
declare module 'utils/lib/string/pascalcase.js' {
  declare module.exports: $Exports<'utils/lib/string/pascalcase'>;
}
declare module 'utils/lib/string/pathcase.js' {
  declare module.exports: $Exports<'utils/lib/string/pathcase'>;
}
declare module 'utils/lib/string/replace.js' {
  declare module.exports: $Exports<'utils/lib/string/replace'>;
}
declare module 'utils/lib/string/reverse.js' {
  declare module.exports: $Exports<'utils/lib/string/reverse'>;
}
declare module 'utils/lib/string/rightAlign.js' {
  declare module.exports: $Exports<'utils/lib/string/rightAlign'>;
}
declare module 'utils/lib/string/sentencecase.js' {
  declare module.exports: $Exports<'utils/lib/string/sentencecase'>;
}
declare module 'utils/lib/string/slugify.js' {
  declare module.exports: $Exports<'utils/lib/string/slugify'>;
}
declare module 'utils/lib/string/snakecase.js' {
  declare module.exports: $Exports<'utils/lib/string/snakecase'>;
}
declare module 'utils/lib/string/toString.js' {
  declare module.exports: $Exports<'utils/lib/string/toString'>;
}
declare module 'utils/lib/string/truncate.js' {
  declare module.exports: $Exports<'utils/lib/string/truncate'>;
}
declare module 'utils/lib/string/wordwrap.js' {
  declare module.exports: $Exports<'utils/lib/string/wordwrap'>;
}
