// flow-typed signature: f99863086e185a02a191e66cdf599781
// flow-typed version: <<STUB>>/webpack-visualizer-plugin_v^0.1.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-visualizer-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-visualizer-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-visualizer-plugin/lib/buildHierarchy' {
  declare module.exports: any;
}

declare module 'webpack-visualizer-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'webpack-visualizer-plugin/lib/pluginmain' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-visualizer-plugin/lib/buildHierarchy.js' {
  declare module.exports: $Exports<'webpack-visualizer-plugin/lib/buildHierarchy'>;
}
declare module 'webpack-visualizer-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'webpack-visualizer-plugin/lib/plugin'>;
}
declare module 'webpack-visualizer-plugin/lib/pluginmain.js' {
  declare module.exports: $Exports<'webpack-visualizer-plugin/lib/pluginmain'>;
}
